[tools]
node = 'lts'
pnpm = 'latest'
rust = { version = "latest", components = "rust-analyzer" }

[settings]
node.default_packages_file = '~/.config/mise/default-npm-packages'
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[hooks]
postinstall = 'mise prune -y'
