[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Underline", blinking = "Always" }

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.normal]
family = "IntoneMono Nerd Font Mono"

[font.bold]
family = "IntoneMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IntoneMono Nerd Font Mono"
style = "Italic"

[font.offset]
y = 6

[terminal.shell]
program = "tmux"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 95
lines = 25

[window.padding]
x = 15
y = 20

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
