live_config_reload = true

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.normal]
family = "0xProto Nerd Font"

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.offset]
y = 6

[shell]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 15
y = 20
