[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["version-control", "file-encoding", "file-line-ending", "file-type"]

[editor.whitespace.render]
tab = "all"
space = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"

[keys.normal]
C-s = ":w"

[keys.insert]
j = { k = "normal_mode" }
