config-version = 2

persistent-workspaces = ["1", "2", "3", "4"]

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

[mode.main.binding]
ctrl-h = 'focus --boundaries all-monitors-outer-frame left'
ctrl-j = 'focus --boundaries all-monitors-outer-frame down'
ctrl-k = 'focus --boundaries all-monitors-outer-frame up'
ctrl-l = 'focus --boundaries all-monitors-outer-frame right'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
ctrl-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
ctrl-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
ctrl-shift-4 = 'move-node-to-workspace --focus-follows-window 4'

ctrl-shift-f = 'fullscreen'
ctrl-shift-t = 'layout tiles accordion'
ctrl-shift-space = 'layout floating tiling'

ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

ctrl-shift-g = 'join-with right'

[workspace-to-monitor-force-assignment]
1 = ['secondary', 'main']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']
